### ISSUE TITLE
remove hp proxy from Dockerfile

### ISSUE THREAD

**Issue by alexei-led** [gaia-adm/result-upload-service#2]
Proxy in Dickerfile is obsolete: you can setup env during build and its not needed for CI

**Comment by jaroslavl1** [comment]
This is not easy. "docker run" supports -e parameter for setting environment, but "docker build" doesn't. Environment variables exported on host building docker image are not propagated during build so apt-get doesn't work and we can't install node.js.

There is a very long discussion at docker about his problem https://github.com/docker/docker/pull/9176

Until they definitely solve it, we either need the CI to execute some shell script that will prepare the Dockerfile (by adding/removing proxy) or use separate Dockerfiles (results in many Dockerfiles)

**Comment by alexei-led** [comment]
Indeed, a problem. 
Do you need help to prepare a shell script? I did something similar for Vagrant file, you can take a look at it, towards the end (`sed` command use). The idea is simple: search for some text pattern and either replace lines with right proxy from the environment or remove these lines.

**Comment by jaroslavl1** [comment]
I ended up solving this problem with a shell script setup.sh that detects the need to use proxy and selects one from fixed list of proxies. It then executes commands that need proxy access. It should work fine both locally and on CircleCI. Its a hack actually but works fine.

Downsides:
- it goes against the idea of Docker of having all RUN commands in it
- fixed list of proxies in the script

Advantages:
- no single hardcoded proxy in Dockerfile
- can work without proxy, or with any of fixed proxies - based on runtime detection
- no need for sed or any other text processor that may not be installed. However it needs bash & curl in the docker image where it executes.
- when building Docker image, one is not really aware of the proxy problem anymore, just use docker in the same way as without proxy, no need to execute anything extra

**Comment by alexei-led** [comment]
Nice trick, I like it. We should use it for other Docker files too.
